-- =============================================================================
-- Xàmpions d'estiu 2019: els scrabbles de cada partida
-- =============================================================================
-- De la taula de scrabbles de l'organització (P1 a P10 per jugador, 2026-10-02).
-- Cada jugador juga una partida per ronda, així que Pk és la ronda k (el
-- Juanjo Corzo juga de la 1 a la 4 i el Xavi Castelló, de la 5 a la 10).
-- Substitueix els que hi havia, que eren copiats d'una partida a l'altra.

CREATE TEMP TABLE scrabbles_taula (nom TEXT, ronda INTEGER, scrabbles INTEGER);
INSERT INTO scrabbles_taula VALUES
('Joan Pascual',1,3),
('Joan Pascual',2,2),
('Joan Pascual',3,5),
('Joan Pascual',4,6),
('Joan Pascual',5,3),
('Joan Pascual',6,3),
('Joan Pascual',7,3),
('Joan Pascual',8,3),
('Joan Pascual',9,4),
('Joan Pascual',10,2),
('Mateu Xurí',1,7),
('Mateu Xurí',2,3),
('Mateu Xurí',3,2),
('Mateu Xurí',4,5),
('Mateu Xurí',5,3),
('Mateu Xurí',6,0),
('Mateu Xurí',7,4),
('Mateu Xurí',8,4),
('Mateu Xurí',9,2),
('Mateu Xurí',10,2),
('Antoni Riera',1,3),
('Antoni Riera',2,4),
('Antoni Riera',3,3),
('Antoni Riera',4,3),
('Antoni Riera',5,6),
('Antoni Riera',6,4),
('Antoni Riera',7,4),
('Antoni Riera',8,2),
('Antoni Riera',9,1),
('Antoni Riera',10,1),
('Andreu Fuster',1,2),
('Andreu Fuster',2,2),
('Andreu Fuster',3,3),
('Andreu Fuster',4,6),
('Andreu Fuster',5,3),
('Andreu Fuster',6,3),
('Andreu Fuster',7,4),
('Andreu Fuster',8,1),
('Andreu Fuster',9,4),
('Andreu Fuster',10,2),
('Maribel Servera',1,3),
('Maribel Servera',2,1),
('Maribel Servera',3,1),
('Maribel Servera',4,3),
('Maribel Servera',5,3),
('Maribel Servera',6,3),
('Maribel Servera',7,3),
('Maribel Servera',8,3),
('Maribel Servera',9,4),
('Maribel Servera',10,4),
('Joan Gelabert',1,2),
('Joan Gelabert',2,4),
('Joan Gelabert',3,3),
('Joan Gelabert',4,3),
('Joan Gelabert',5,2),
('Joan Gelabert',6,3),
('Joan Gelabert',7,2),
('Joan Gelabert',8,3),
('Joan Gelabert',9,1),
('Joan Gelabert',10,2),
('Lina Maria Riera',1,3),
('Lina Maria Riera',2,2),
('Lina Maria Riera',3,3),
('Lina Maria Riera',4,2),
('Lina Maria Riera',5,4),
('Lina Maria Riera',6,2),
('Lina Maria Riera',7,3),
('Lina Maria Riera',8,1),
('Lina Maria Riera',9,1),
('Lina Maria Riera',10,3),
('Tomeu Riera',1,3),
('Tomeu Riera',2,1),
('Tomeu Riera',3,2),
('Tomeu Riera',4,4),
('Tomeu Riera',5,3),
('Tomeu Riera',6,1),
('Tomeu Riera',7,3),
('Tomeu Riera',8,2),
('Tomeu Riera',9,3),
('Tomeu Riera',10,2),
('Xisco Truyols',1,2),
('Xisco Truyols',2,2),
('Xisco Truyols',3,3),
('Xisco Truyols',4,2),
('Xisco Truyols',5,2),
('Xisco Truyols',6,3),
('Xisco Truyols',7,2),
('Xisco Truyols',8,2),
('Xisco Truyols',9,4),
('Xisco Truyols',10,1),
('Pere Grimalt Riera',1,2),
('Pere Grimalt Riera',2,5),
('Pere Grimalt Riera',3,0),
('Pere Grimalt Riera',4,3),
('Pere Grimalt Riera',5,1),
('Pere Grimalt Riera',6,3),
('Pere Grimalt Riera',7,3),
('Pere Grimalt Riera',8,4),
('Pere Grimalt Riera',9,1),
('Pere Grimalt Riera',10,1),
('Miquela Grimalt',1,3),
('Miquela Grimalt',2,3),
('Miquela Grimalt',3,2),
('Miquela Grimalt',4,1),
('Miquela Grimalt',5,4),
('Miquela Grimalt',6,2),
('Miquela Grimalt',7,1),
('Miquela Grimalt',8,1),
('Miquela Grimalt',9,3),
('Miquela Grimalt',10,2),
('M. M. Matamalas',1,3),
('M. M. Matamalas',2,2),
('M. M. Matamalas',3,1),
('M. M. Matamalas',4,3),
('M. M. Matamalas',5,3),
('M. M. Matamalas',6,1),
('M. M. Matamalas',7,2),
('M. M. Matamalas',8,2),
('M. M. Matamalas',9,3),
('M. M. Matamalas',10,2),
('Margalida Bonnín',1,2),
('Margalida Bonnín',2,0),
('Margalida Bonnín',3,3),
('Margalida Bonnín',4,3),
('Margalida Bonnín',5,2),
('Margalida Bonnín',6,3),
('Margalida Bonnín',7,2),
('Margalida Bonnín',8,3),
('Margalida Bonnín',9,2),
('Margalida Bonnín',10,2),
('Roger Cosso',1,2),
('Roger Cosso',2,3),
('Roger Cosso',3,4),
('Roger Cosso',4,1),
('Roger Cosso',5,3),
('Roger Cosso',6,0),
('Roger Cosso',7,2),
('Roger Cosso',8,2),
('Roger Cosso',9,2),
('Roger Cosso',10,2),
('Esperança Martí',1,1),
('Esperança Martí',2,0),
('Esperança Martí',3,0),
('Esperança Martí',4,5),
('Esperança Martí',5,4),
('Esperança Martí',6,3),
('Esperança Martí',7,3),
('Esperança Martí',8,0),
('Esperança Martí',9,2),
('Esperança Martí',10,3),
('Aina Garcia',1,3),
('Aina Garcia',2,2),
('Aina Garcia',3,2),
('Aina Garcia',4,2),
('Aina Garcia',5,2),
('Aina Garcia',6,0),
('Aina Garcia',7,1),
('Aina Garcia',8,1),
('Aina Garcia',9,2),
('Aina Garcia',10,4),
('Joan Llodrà',1,1),
('Joan Llodrà',2,2),
('Joan Llodrà',3,3),
('Joan Llodrà',4,2),
('Joan Llodrà',5,1),
('Joan Llodrà',6,1),
('Joan Llodrà',7,2),
('Joan Llodrà',8,3),
('Joan Llodrà',9,2),
('Joan Llodrà',10,2),
('Cati Sureda',1,1),
('Cati Sureda',2,2),
('Cati Sureda',3,2),
('Cati Sureda',4,0),
('Cati Sureda',5,3),
('Cati Sureda',6,1),
('Cati Sureda',7,4),
('Cati Sureda',8,3),
('Cati Sureda',9,2),
('Cati Sureda',10,0),
('Pere Grimalt Vert',1,2),
('Pere Grimalt Vert',2,2),
('Pere Grimalt Vert',3,3),
('Pere Grimalt Vert',4,2),
('Pere Grimalt Vert',5,1),
('Pere Grimalt Vert',6,2),
('Pere Grimalt Vert',7,2),
('Pere Grimalt Vert',8,1),
('Pere Grimalt Vert',9,1),
('Pere Grimalt Vert',10,1),
('Mar Bel',1,1),
('Mar Bel',2,2),
('Mar Bel',3,5),
('Mar Bel',4,0),
('Mar Bel',5,1),
('Mar Bel',6,2),
('Mar Bel',7,1),
('Mar Bel',8,0),
('Mar Bel',9,2),
('Mar Bel',10,2),
('Bel Llull',1,1),
('Bel Llull',2,2),
('Bel Llull',3,3),
('Bel Llull',4,1),
('Bel Llull',5,1),
('Bel Llull',6,3),
('Bel Llull',7,1),
('Bel Llull',8,1),
('Bel Llull',9,1),
('Bel Llull',10,2),
('Jaume Rigo',1,2),
('Jaume Rigo',2,3),
('Jaume Rigo',3,1),
('Jaume Rigo',4,1),
('Jaume Rigo',5,0),
('Jaume Rigo',6,0),
('Jaume Rigo',7,1),
('Jaume Rigo',8,2),
('Jaume Rigo',9,1),
('Jaume Rigo',10,3),
('Marta Servera',1,3),
('Marta Servera',2,1),
('Marta Servera',3,1),
('Marta Servera',4,0),
('Marta Servera',5,1),
('Marta Servera',6,0),
('Marta Servera',7,1),
('Marta Servera',8,2),
('Marta Servera',9,2),
('Marta Servera',10,2),
('Jaume Vives',1,0),
('Jaume Vives',2,0),
('Jaume Vives',3,1),
('Jaume Vives',4,1),
('Jaume Vives',5,1),
('Jaume Vives',6,1),
('Jaume Vives',7,1),
('Jaume Vives',8,1),
('Jaume Vives',9,3),
('Jaume Vives',10,3),
('Llorenç Carreres',1,2),
('Llorenç Carreres',2,1),
('Llorenç Carreres',3,1),
('Llorenç Carreres',4,2),
('Llorenç Carreres',5,1),
('Llorenç Carreres',6,0),
('Llorenç Carreres',7,1),
('Llorenç Carreres',8,0),
('Llorenç Carreres',9,0),
('Llorenç Carreres',10,3),
('Bernat Amer',1,1),
('Bernat Amer',2,1),
('Bernat Amer',3,0),
('Bernat Amer',4,0),
('Bernat Amer',5,1),
('Bernat Amer',6,2),
('Bernat Amer',7,0),
('Bernat Amer',8,2),
('Bernat Amer',9,1),
('Bernat Amer',10,2),
('Carles Díez',1,0),
('Carles Díez',2,1),
('Carles Díez',3,1),
('Carles Díez',4,0),
('Carles Díez',5,2),
('Carles Díez',6,1),
('Carles Díez',7,2),
('Carles Díez',8,2),
('Carles Díez',9,0),
('Carles Díez',10,1),
('Joana Maria Pasqual',1,0),
('Joana Maria Pasqual',2,1),
('Joana Maria Pasqual',3,1),
('Joana Maria Pasqual',4,0),
('Joana Maria Pasqual',5,1),
('Joana Maria Pasqual',6,1),
('Joana Maria Pasqual',7,1),
('Joana Maria Pasqual',8,2),
('Joana Maria Pasqual',9,2),
('Joana Maria Pasqual',10,0),
('Francesc Vernet',1,0),
('Francesc Vernet',2,1),
('Francesc Vernet',3,1),
('Francesc Vernet',4,0),
('Francesc Vernet',5,1),
('Francesc Vernet',6,1),
('Francesc Vernet',7,1),
('Francesc Vernet',8,0),
('Francesc Vernet',9,0),
('Francesc Vernet',10,1),
('Juanjo Corzo',1,1),
('Juanjo Corzo',2,1),
('Juanjo Corzo',3,2),
('Juanjo Corzo',4,0),
('Sebastiana Mascaró',1,0),
('Sebastiana Mascaró',2,0),
('Sebastiana Mascaró',3,1),
('Sebastiana Mascaró',4,0),
('Sebastiana Mascaró',5,1),
('Sebastiana Mascaró',6,0),
('Sebastiana Mascaró',7,1),
('Sebastiana Mascaró',8,1),
('Sebastiana Mascaró',9,0),
('Sebastiana Mascaró',10,0),
('Margalida Rosselló',1,1),
('Margalida Rosselló',2,0),
('Margalida Rosselló',3,1),
('Margalida Rosselló',4,1),
('Margalida Rosselló',5,0),
('Margalida Rosselló',6,0),
('Margalida Rosselló',7,0),
('Margalida Rosselló',8,0),
('Margalida Rosselló',9,0),
('Margalida Rosselló',10,1),
('Xavi Castelló',5,1),
('Xavi Castelló',6,0),
('Xavi Castelló',7,0),
('Xavi Castelló',8,0),
('Xavi Castelló',9,1),
('Xavi Castelló',10,1);

DO $$
DECLARE
    v_camp UUID := (SELECT id FROM campionats WHERE nom = 'Xàmpions d''estiu 2019');
    v_falten INTEGER;
BEGIN
    IF v_camp IS NULL THEN
        RETURN;
    END IF;

    -- Cada valor de la taula ha de tenir la seva partida.
    SELECT count(*) INTO v_falten
    FROM scrabbles_taula t
    JOIN jugadors j ON j.nom_complet = t.nom
    WHERE NOT EXISTS (
        SELECT 1 FROM partides p
        WHERE p.campionat_id = v_camp AND p.ronda = t.ronda AND j.id IN (p.jugador_1_id, p.jugador_2_id));
    IF v_falten > 0 OR (SELECT count(*) FROM scrabbles_taula t JOIN jugadors j ON j.nom_complet = t.nom) <> 320 THEN
        RAISE EXCEPTION 'Xàmpions 2019: la taula de scrabbles no casa amb les partides (% sense partida)', v_falten;
    END IF;

    UPDATE partides p
    SET scrabbles_1 = (SELECT t.scrabbles FROM scrabbles_taula t JOIN jugadors j ON j.nom_complet = t.nom
                       WHERE j.id = p.jugador_1_id AND t.ronda = p.ronda),
        scrabbles_2 = (SELECT t.scrabbles FROM scrabbles_taula t JOIN jugadors j ON j.nom_complet = t.nom
                       WHERE j.id = p.jugador_2_id AND t.ronda = p.ronda)
    WHERE p.campionat_id = v_camp;
END $$;

DROP TABLE scrabbles_taula;
